### ISSUE TITLE
NanoPi_APA102 - Node Module?

### ISSUE THREAD

**Issue by JimmyPesto** [leonyuhanov/NanoPi_APA102#1]
I need to use APA102 LEDs from Node.js so i thought about building a Node Module based on this C-Code.
Is someone else interested in building this? I could need some help.

**Comment by leonyuhanov** [comment]
Nodejs already has an spi module you could use,but its about 100 times slower than c code

**Comment by JimmyPesto** [comment]
There are modules like "node-apa102-spi" but they do `require('rpio')` which is not compatible with NanoPi so far.
Do you know a SPI module which works on Nano Pi's?

**Comment by leonyuhanov** [comment]
For NodeJS? No i dont.
